name: CI/CD Pipeline

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        run: docker build -t aleksandarMilev/nest-demo -f Dockerfile.dev .

      - name: Create test env file
        run: |
          cp .env.example .env.dev
          sed -i 's/^NODE_ENV=.*/NODE_ENV=test/' .env.dev
          sed -i 's|^DATABASE_URL=.*|DATABASE_URL=postgres://user:pass@localhost:5432/ci|' .env.dev

      - name: Run Jest tests
        run: docker run --env-file .env.dev -e CI=true aleksandarMilev/nest-demo npm run test:cov

      - name: Build production (optional, local verify)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker build -t nest-demo:prod -f Dockerfile.prod .

      - name: Create deployment package
        if: ${{ github.ref == 'refs/heads/master' }}
        run: zip -r dist.zip dist package.json package-lock.json Dockerfile.prod

      - name: Deploy to Elastic Beanstalk
        if: ${{ github.ref == 'refs/heads/master' && env.AWS_ACCESS_KEY != '' && env.AWS_SECRET_KEY != '' }}
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ env.AWS_SECRET_KEY }}
          application_name: "nest demo"
          environment_name: "Nestdemo-env"
          region: "eu-north-1"
          version_label: ${{ github.run_number }}
          deployment_package: "./dist.zip"
