name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - api-service
          - worker
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        working-directory: ./${{ matrix.service }}
        run: docker build -t ${{ matrix.service }}-dev -f Dockerfile.dev .

      - name: Create test env
        working-directory: ./${{ matrix.service }}
        run: |
          cp .env.example .env.dev || true
          sed -i 's/^NODE_ENV=.*/NODE_ENV=test/' .env.dev || true

      - name: Run tests in container
        working-directory: ./${{ matrix.service }}
        run: docker run --rm --env-file .env.dev -e CI=true ${{ matrix.service }}-dev npm run test:cov

  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        working-directory: ./client
        run: npm ci
      - name: Typecheck & build
        working-directory: ./client
        run: npm run build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [test-services, build-client]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build & push prod images / deploy (ECR/EB/ECS)
  #       run: echo "wire the prod deploy here"
